### ISSUE TITLE
Considering changing to TailwindCSS

### ISSUE THREAD

**Issue by ukayaj620** [bios-bunda-mulia-university/himabios#4]
Do you have any consideration for using TailwindCSS for styling instead of using the UI components from ChakraUI?

**Comment by AlphaByte-RedTeam** [comment]
Thank you for reaching me. I use Chakra UI as my go-to UI provider because I've struggled to use Tailwind. Tailwind is a great library, but it makes debugging really difficult for me. A lot of `classes` yields longer `className` and it makes more difficult to read. I use Chakra UI because Chakra is built on top of Tailwind. It also has a pre-built component to easily use which React recommended.

If you have further question. Let me know.
Thank you.

Regards,
Andrew V. Victorio

**Comment by AlphaByte-RedTeam** [comment]
> Thank you for reaching me. I use Chakra UI as my go-to UI provider because I've struggled to use Tailwind. Tailwind is a great library, but it makes debugging really difficult for me. A lot of `classes` yields longer `className` and it makes more difficult to read. I use Chakra UI because Chakra is built on top of Tailwind. It also has a pre-built component to easily use which React recommended.
> 
> If you have further question. Let me know. Thank you.
> 
> Regards, Andrew V. Victorio

After thinking a lot of research and testing, I will migrate from chakra UI to tailwind CSS. Thank you for the proposal. It helps a lot.

Regards,
Andrew V. Victorio
